# Generated by Django 4.2.8 on 2023-12-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='branchcompanycaseassignmentdetail',
            old_name='branchid',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='branchcompanycaseassignmentdetail',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='caseassignmentdetail',
            old_name='caseid',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='caseassignmentdetail',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='caseregister',
            old_name='branchid',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='caseregister',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='caseregister',
            old_name='priorityid',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='clientinvoices',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientquotations',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='communicationdetails',
            old_name='communicationid',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='communications',
            old_name='channelid',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='branchid',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='productid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='serviceid',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='projecttaskprogress',
            old_name='taskid',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='projecttasks',
            old_name='projectid',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='taskassignmentdetail',
            old_name='taskid',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskassignmentdetail',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='branchid',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profileid',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='main.userprofile'),
        ),
    ]
